apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: conf-service
  namespace: qp
spec:
  rules:
  - host: "||host||"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: conf-service
            port:
              number: 80      