apiVersion: v1
kind: PersistentVolume
metadata:
  name: qp-pv
  namespace: dpc-consolidation
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /volume1/msckubepv/qp_config
    server: 172.16.4.200