apiVersion: v1
kind: Service
metadata:
  name: configuration-service
  namespace: dpc-consolidation
spec:
  type: ClusterIP
  selector:
    app: configuration-service
  ports:
  - port: 80
    targetPort: 80